### ISSUE TITLE
My Cookbooks page does not load

### ISSUE THREAD

**Issue by alittlebroken** [alittlebroken/recipefinder-client#86]
No page content loads at all when trying to access the My Cookbooks page for a new user

**Comment by alittlebroken** [comment]
Page now displays correctly when  no cookbooks exist at all and informs the user they have no cookbooks at all and allows themk to create one.

However, when you create a new cookbook, the whole page reloads the user gets logged out of the site ( as expected if the page refreshes ) and still no cookbook listed for the new user.

**Comment by alittlebroken** [comment]
console.log reports the following when a new cookbook is submitted

Form.js:55 Uncaught TypeError: props.submit is not a function
    at onSubmit (:3000/static/js/bundle.js:17432:76)
    at HTMLUnknownElement.callCallback (:3000/static/js/bundle.js:135021:18)
    at Object.invokeGuardedCallbackDev (:3000/static/js/bundle.js:135065:20)
    at invokeGuardedCallback (:3000/static/js/bundle.js:135120:35)
    at invokeGuardedCallbackAndCatchFirstError (:3000/static/js/bundle.js:135134:29)
    at executeDispatch (:3000/static/js/bundle.js:138756:7)
    at processDispatchQueueItemsInOrder (:3000/static/js/bundle.js:138782:11)
    at processDispatchQueue (:3000/static/js/bundle.js:138793:9)
    at dispatchEventsForPlugins (:3000/static/js/bundle.js:138802:7)
    at :3000/static/js/bundle.js:138980:16

**Comment by alittlebroken** [comment]
The issue was caused by Form component have the incorrect prop name for the submit handler. Worked a charm after this.

Now just need to deal with why it was not created when the user was

**Comment by alittlebroken** [comment]
It was not created as the system was not designed that way from the front end, it needs to be done from the backend

**Comment by alittlebroken** [comment]
A default cookbook is now created in the backend
